version: "3"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: booking-hotel-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: booking-hotel-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - "8080:8080"
      - "8443:8443"
    command: start-dev

volumes:
  sqlserver_data:
